// 1. Grab DOM Elements
const form = document.getElementById('automod-form');
const yamlOutput = document.getElementById('yaml-output');
const copyBtn = document.getElementById('copy-btn');

// Checkboxes and their sub-menus
const pinnedToggle = document.getElementById('pinned-comment-toggle');
const pinnedSettings = document.getElementById('pinned-comment-settings');
const pinnedText = document.getElementById('pinned-comment-text');
const pinnedLock = document.getElementById('pinned-comment-lock');

// User Filter Elements
const ageToggle = document.getElementById('age-filter-toggle');
const ageSettings = document.getElementById('age-filter-settings');
const ageDays = document.getElementById('age-days');
const ageTarget = document.getElementById('age-target');
const ageAction = document.getElementById('age-action');

const karmaToggle = document.getElementById('karma-filter-toggle');
const karmaSettings = document.getElementById('karma-filter-settings');
const karmaType = document.getElementById('karma-type');
const karmaTarget = document.getElementById('karma-target');
const karmaAmount = document.getElementById('karma-amount');
const karmaAction = document.getElementById('karma-action');

// 2. UI Toggle Logic
function updateUI() {
    // Pinned Comment
    if (pinnedToggle.checked) {
        pinnedSettings.classList.add('visible');
    } else {
        pinnedSettings.classList.remove('visible');
    }

    // Account Age
    if (ageToggle.checked) {
        ageSettings.classList.add('visible');
    } else {
        ageSettings.classList.remove('visible');
    }

    // Karma Filter
    if (karmaToggle.checked) {
        karmaSettings.classList.add('visible');
    } else {
        karmaSettings.classList.remove('visible');
    }
}

// 3. YAML Compiler
function generateYAML() {
    let yaml = `# Generated by AutoMod Generator\n---\n`;
    let hasRules = false;

    // Rule: Pinned Welcome Comment
    if (pinnedToggle.checked && pinnedText.value.trim() !== "") {
        hasRules = true;
        yaml += `type: submission\n`;
        
        const indentedComment = pinnedText.value.split('\n').map(line => `    ${line}`).join('\n');
        yaml += `comment: |\n${indentedComment}\n`;
        yaml += `comment_stickied: true\n`;
        
        if (pinnedLock.checked) {
            yaml += `comment_locked: true\n`;
        }
        
        yaml += `---\n`;
    }

    // Rule: Account Age Filter
    if (ageToggle.checked && ageDays.value > 0) {
        hasRules = true;
        yaml += `type: ${ageTarget.value}\n`; // UPDATED
        yaml += `author:\n`;
        yaml += `    account_age: "< ${ageDays.value} days"\n`;
        yaml += `    is_moderator: false\n`; 
        yaml += `action: ${ageAction.value}\n`;
        yaml += `action_reason: "Account is younger than ${ageDays.value} days"\n`;
        yaml += `---\n`;
    }

    // Rule: Low Karma Filter
    if (karmaToggle.checked && karmaAmount.value !== "") {
        hasRules = true;
        yaml += `type: ${karmaTarget.value}\n`; // UPDATED
        yaml += `author:\n`;
        yaml += `    ${karmaType.value}: "< ${karmaAmount.value}"\n`;
        yaml += `    is_moderator: false\n`;
        yaml += `action: ${karmaAction.value}\n`;
        
        const readableKarmaType = karmaType.options[karmaType.selectedIndex].text;
        yaml += `action_reason: "User has less than ${karmaAmount.value} ${readableKarmaType}"\n`;
        yaml += `---\n`;
    }

    if (!hasRules) {
        yaml = `# Select a rule on the left to generate code...`;
    }

    yamlOutput.textContent = yaml;
}

// 4. Event Listeners
function updateAll() {
    updateUI();
    generateYAML();
}

// Catch both typing events (input) and dropdown selections (change)
form.addEventListener('input', updateAll);
form.addEventListener('change', updateAll);

copyBtn.addEventListener('click', () => {
    const textToCopy = yamlOutput.textContent;
    if (textToCopy === `# Select a rule on the left to generate code...`) return;

    navigator.clipboard.writeText(textToCopy).then(() => {
        const originalText = copyBtn.textContent;
        copyBtn.textContent = 'Copied!';
        copyBtn.style.backgroundColor = '#28a745';

        setTimeout(() => {
            copyBtn.textContent = originalText;
            copyBtn.style.backgroundColor = 'var(--primary)';
        }, 2000);
    }).catch(err => {
        console.error('Failed to copy: ', err);
    });
});
