// 1. Grab DOM Elements
const form = document.getElementById('automod-form');
const yamlOutput = document.getElementById('yaml-output');
const copyBtn = document.getElementById('copy-btn');

// Checkboxes and their sub-menus
const pinnedToggle = document.getElementById('pinned-comment-toggle');
const pinnedSettings = document.getElementById('pinned-comment-settings');
const pinnedText = document.getElementById('pinned-comment-text');
const pinnedLock = document.getElementById('pinned-comment-lock'); // NEW

// 2. UI Toggle Logic
function updateUI() {
    if (pinnedToggle.checked) {
        pinnedSettings.classList.add('visible');
    } else {
        pinnedSettings.classList.remove('visible');
    }
}

// 3. YAML Compiler
function generateYAML() {
    let yaml = `# Generated by AutoMod Generator\n---\n`;
    let hasRules = false;

    // Rule: Pinned Welcome Comment
    if (pinnedToggle.checked && pinnedText.value.trim() !== "") {
        hasRules = true;
        yaml += `type: submission\n`;
        
        const indentedComment = pinnedText.value.split('\n').map(line => `    ${line}`).join('\n');
        yaml += `comment: |\n${indentedComment}\n`;
        yaml += `comment_stickied: true\n`;
        
        // NEW: Only lock the comment if the user explicitly wants to
        if (pinnedLock.checked) {
            yaml += `comment_locked: true\n`;
        }
        
        yaml += `---\n`;
    }

    if (!hasRules) {
        yaml = `# Select a rule on the left to generate code...`;
    }

    yamlOutput.textContent = yaml;
}

// 4. Event Listeners
form.addEventListener('input', () => {
    updateUI();
    generateYAML();
});

copyBtn.addEventListener('click', () => {
    const textToCopy = yamlOutput.textContent;
    if (textToCopy === `# Select a rule on the left to generate code...`) return;

    navigator.clipboard.writeText(textToCopy).then(() => {
        const originalText = copyBtn.textContent;
        copyBtn.textContent = 'Copied!';
        copyBtn.style.backgroundColor = '#28a745';

        setTimeout(() => {
            copyBtn.textContent = originalText;
            copyBtn.style.backgroundColor = 'var(--primary)';
        }, 2000);
    }).catch(err => {
        console.error('Failed to copy: ', err);
    });
});
